apiVersion: v1
kind: Service
metadata:
  name: zuri-backend-service
spec:
  selector:
    app: zuri-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
  type: NodePort