apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuri-backend
  template:
    metadata:
      labels:
        app: zuri-backend
    spec:
      containers:
        - name: zuri-backend
          image: nfisu/zuri-backend:latest
          ports:
            - containerPort: 5000